### PR TITLE
Minimal scene GUI configuration file

### PR DESCRIPTION
**Pull request by Thodoris1999**
Addresses #77 

Chooses between legacy `Scene3D` config file and new `MinimalScene`.

Now it should be straightforward to add tape measuring, camera following, etc.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
You should clean the history

```bash
git rebase -i HEAD~2
# remove the line with the commit `Add fortress support` and save
git push -f origin minimal_scene
```

**Comment by Thodoris1999** [comment]
@ahcorde done

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to merge this with `main` ?  Now CI should work

**Review by ahcorde — CHANGES_REQUESTED** [review]
We can just keep the fortress configuration

**Comment by Thodoris1999** [comment]
@ahcorde I can't test it since I dropped the fortress support config in this branch, but pretty sure it's correct.

**Review by ahcorde — CHANGES_REQUESTED** [review]
You need to merge this with `main`:

```bash
git remote add ignition https://github.com/ignitionrobotics/ign-rviz
git fetch ignition
git merge ignition/main
```

**Comment by Thodoris1999** [comment]
Oh makes sense, I though you meant we need to merge this **into** main :woman_facepalming:

Tested it by publishing a pose `ros2 topic pub /test geometry_msgs/msg/PoseS│[GUI] [Msg] Loading plugin [ignition-rendering-ogre]
tamped '{header: {frame_id: "world"}, pose: {position: {x: 1, y: 1, z: 1}, orientation: {x: 0, y: 0, │[GUI] [Dbg] [MinimalScene.cc:609] Destroy scene [scene]
z: 0.4794255, w: 0.8775826}}}' ` and panning around, it seems to work.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Thank you @Thodoris1999

By the way, `Grid` is not working, do you mind to review it ?

**Comment by Thodoris1999** [comment]
Sure, you can assign me to it.

**Pull request merged**
